### PR TITLE
Add script for tabulating method invalidations

### PR DESCRIPTION
**Pull request by charleskawczynski**
This is to replace [these plots](https://github.com/CliMA/TurbulenceConvection.jl/pull/673#issue-1087066143).

### CODE REVIEW

**Comment by jakebolewski** [comment]
what does method name mean here? https://github.com/CliMA/ReportMetrics.jl/runs/4858932446?check_suite_focus=true#step:6:142

**Review by jakebolewski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
> what does method name mean here? https://github.com/CliMA/ReportMetrics.jl/runs/4858932446?check_suite_focus=true#step:6:142

Good question, is really just the function name, let me see if there's maybe more info that can be added to this. I'll need to peek around in the `invalidations` object

**Comment by charleskawczynski** [comment]
Actually, I think this is fine. I've mostly used this in the past to identify / monitor egregious invalidations. Also, having the file/line number is kind of enough to see the particular method.

**Comment by jakebolewski** [comment]
I think I was confused, but the invalidating methods are `==` and `*` which make sense

**Comment by charleskawczynski** [comment]
Ah, that's a good idea, I'll see if I can find that info

**Comment by charleskawczynski** [comment]
I added the module specified in the method (property, from the invalidation struct), and we get something like this:

```
┌─────────────────────────────────────────────────────┬───────────────────┬───────────────┬─────────────────┐
│ <file name>:<line number>                           │    Method Name    │ Invalidations │ Invalidations % │
│                                                     │                   │    Number     │     (xᵢ/∑x)     │
├─────────────────────────────────────────────────────┼───────────────────┼───────────────┼─────────────────┤
│ ChainRulesCore/oBjCg/src/tangent_types/thunks.jl:29 │ ChainRulesCore.== │      179      │       63        │
│ ChainRulesCore/oBjCg/src/tangent_types/thunks.jl:28 │ ChainRulesCore.== │      104      │       36        │
│ ChainRulesCore/oBjCg/src/tangent_arithmetic.jl:105  │ ChainRulesCore.*  │       2       │        1        │
└─────────────────────────────────────────────────────┴───────────────────┴───────────────┴─────────────────┘
```

Obviously, `==` is first defined in `Base`, but overloaded/invalidated in `ChainRulesCore` I think it might be fine to use the name only (`==`), since we already get the info of who's overloading/invalidating from the file info.

**Comment by charleskawczynski** [comment]
Let's merge this for now and we can work on adding more details to the table later.

**Pull request merged**
